#!/bin/bash

domain=$(sudo yunohost app setting openid domain)
sudo rm -f /etc/nginx/conf.d/$domain.d/openid.conf

sudo rm -rf /var/www/openid
sudo rm -f /var/log/openid

sudo service nginx reload
sudo yunohost app ssowatconf
