#!/bin/bash

domain=$(sudo yunohost app setting openidldap domain)
path=$(sudo yunohost app setting openidldap path)

currentdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$current_dir/remove
$current_dir/install $domain $path
